### ISSUE TITLE
scaling of gene name track height

### ISSUE THREAD

**Issue by rgilsbach** [maxplanck-ie/HiCBrowser#16]
depending on the number of genes in the selected genic region the gene annotation track is either clipped or the genes are displayed at very large scale.
Would a dynamic scaling be possible (track height defined by number of overlapping genes).

**Comment by fidelram** [comment]
There are two ways to  solve this. One is to set the maximum number of 'gene rows' to be plotted using `gene rows = n`, where `n` is the number of gene rows that want to be plotted. If a larger number of gene rows is needed, then only up to n rows are shown and some genes may be missing. 

Other solution is to set `global max row = yes`, which will identify the maximum number of genes row needed given the .bed file and this number is always used.
