### ISSUE TITLE
HIC browser image is not appearing properly

### ISSUE THREAD

**Issue by mparida85** [maxplanck-ie/HiCBrowser#26]
Hi All
First, thank you very much for creating a web based tool so we can visualize our tracks on it. It is awesome.
However, I have been struggling to visualize my data.
I have followed the suggestions on installing Hicbrowser and editing the config file but it is not working properly.
I am using an ubuntu operating system and google chrome to visualize the example tracks such as H3K36me3.bw and H3K27me3.bw from modendcode.
The tracks are loading but they are cutting off and the visualization is not useful after they load. I will be very grateful for your concern if you guys can kindly point me the errors in my file and show me the right way to edit the config file. I am very new to this. 

Here are the details of my config files:

filename: browserConfig.ini

[general]
tracks= gene_tracks.ini
TAD intervals= domains.bed
genes= dm3_genes.bed.gz

[browser]
tracks=tracks.ini

filename: gene_tracks.ini

[TADs]
file = <myfile>_domains.bed
title = peaks
color = red
width = 3
file_type = boundaries

[x-axis]
fontsize=10

[spacer]

[genes]
file = <my_genes>.bed
title = genes
color = darkblue
width = 15
labels = on
type = genes
file_type = bed
fontsize = 10

filename: tracks.ini

[hic]
file = Li_et_al_2015.h5
title = Li_et_al_2015
colormap = RdYlBu_r
depth = 100000
min_value =2.8
max_value = 3.0
file_type = hic_matrix
show_masked_bins = yes
scale factor = 1

[x-axis]
fontsize=20
where=top

[spacer]

[x-axis]
fontsize=10
where=top

[spacer]

[bigwig]
file = H3K36me3.bw
title = H3K36me3
color = black
width = 1.5
min_value = 0
max_value = auto
number of bins = 500
nans to zeros = True
type = points
show data range = yes
scale factor = 0.25
file_type = bigwig

[spacer]

[bigwig]
file = H3K27me3.bw
title = H3K27me3
color = red
width = 1.5
min_value = 0
max_value = auto
number of bins = 500
nans to zeros = True
type = points
show data range = yes
scale factor = 0.25
file_type = bigwig

Appreciate your help.
![screenshot from 2018-05-07 15-13-36](https://user-images.githubusercontent.com/27943518/39772007-a84544c8-52b9-11e8-94b5-e8ee7afefdb8.png)

Thanking you
Rocky

**Comment by fidelram** [comment]
I still dont't understand very well your problem. But I see that the H3K36me3 track is not showing. Pay attention to the terminal output where any problem is printed.

Also, the following configuration may give you better results:

```ini
filename: tracks.ini

[x-axis]
fontsize=20
where=top

[hic]
file = Li_et_al_2015.h5
title = Li_et_al_2015
colormap = RdYlBu_r
depth = 1000000
min_value =2.8
max_value = 3.0
file_type = hic_matrix
show_masked_bins = yes
#scale factor = 1

[bigwig]
file = H3K36me3.bw
title = H3K36me3
color = black
width = 3
min_value = 0
max_value = auto
number of bins = 500
nans to zeros = True
#type = points
show data range = yes
scale factor = 0.25
file_type = bigwig

[spacer]
width = 0.5

[bigwig]
file = H3K27me3.bw
title = H3K27me3
color = red
width = 1.5
min_value = 0
max_value = auto
number of bins = 500
nans to zeros = True
#type = points
show data range = yes
scale factor = 0.25
file_type = bigwig
```

**Comment by gtrichard** [comment]
Hello Rocky and thank you for using hicBrowser.

For @fidelram, there is a small typo at the end, take care of not copy/pasting the " ```  " at the end.

Which version of hicBrowser / HiCExplorer are you using?

Take care also of loading a previously "unexplored" region when you are bringing changes to the .ini file.

**Comment by mparida85** [comment]
Hi All
Thank you very much for getting back to me. Appreciate the config edits Dr.Ramirez. I did try them and I still see the images cutoff. Please let me know how I can improve in this direction.
Here are some command logs and images for you to help me better.
![run_server_2018-05-09 10-48-39](https://user-images.githubusercontent.com/27943518/39826361-0a888a9e-537a-11e8-8d00-64e3750bab7b.jpg)
![screenshot from 2018-05-09 10-50-01](https://user-images.githubusercontent.com/27943518/39826359-0a762840-537a-11e8-991c-ccca22d39205.png)
![screenshot from 2018-05-09 10-50-13](https://user-images.githubusercontent.com/27943518/39826358-0a56f2d6-537a-11e8-8ba1-43dc4240fb98.png)
![screenshot from 2018-05-09 10-50-17](https://user-images.githubusercontent.com/27943518/39826357-0a3f306a-537a-11e8-859d-a9d8a0c039ee.png)


Dr. Richard I am using HiCExplorer-2.1.2.tar.gz and the most recent version of the HiC browser.
Please let me know if there is anything I need do to make the H3K27me3 and H3K4me3 tracks appear independent and complete. 
I am very grateful for your help.
Rocky

**Comment by vivekbhr** [comment]
You can try adding a <Gene> track or a <spacer> track at the end to make the last track more visible.
Best,
Vivek

**Comment by mparida85** [comment]
Hi Vivek 
Thank you very much for your response. I think you are suggesting me to add a null track at the end of

**Comment by mparida85** [comment]
Hi Vivek 
Thank you very much for your response. Appreciate it. I will try this approach and see if this works for me. I think you are suggesting me to add a track such as a bigwig (may be just copy paste the H3K27me3 again) to the end that will lift the last track up. If you do not mind is there any other way to separate the two tracks entirely, I thought the spacer attribute was supposed to do that but then may be not. I am very grateful for all your suggestions and help. 
Rocky

**Comment by mparida85** [comment]
Hi All 
I am extremely appreciative of all your suggestions, time you guys took out of your schedule to help me with my issue. After Vivek's suggestion, I decided to add more than one spacer attribute to my config file and it resolved my issue as follows:
[bigwig]
file = H3K36me3.bw
title = H3K36me3
color = black
width = 3
min_value = 0
max_value = auto
number of bins = 500
nans to zeros = True
#type = points
show data range = yes
scale factor = 0.25
file_type = bigwig

[spacer]
width = 0.5

[spacer]
width = 0.5

[spacer]
width = 0.5

[bigwig]
file = H3K27me3.bw
title = H3K27me3
color = red
width = 1.5
min_value = 0
max_value = auto
number of bins = 500
nans to zeros = True
#type = points
show data range = yes
scale factor = 0.25
file_type = bigwig
![screenshot from 2018-05-10 11-13-52](https://user-images.githubusercontent.com/27943518/39880392-4365a1d4-5443-11e8-86ea-3ed15250ae62.png)
Have a good day guys. 
Rocky

**Comment by vivekbhr** [comment]
@mparida85 glad it worked.

**Comment by fidelram** [comment]
In principle, the three spacers can be replaced by a single with with `width = 1.5`. 

Also, you can add an spacer at the end of the configuration if you don't like that the last track is shown with out an space with respect to the layout.

Consider also setting `min_value = auto` for the bigwig files to get a better overview of the data and set log1p transform for the Hi-C track for better results.
